# build.yml
---
platform: linux

inputs:
- name: hub
- name: tooling-ci

outputs:
- name: tooling-ci

params:
  BASELINE:

run:
  path: bash
  args:
  - "-c"
  - |

    IFS=$'\n'

    printf "#################################################\n"
    printf "# Building TOOLING CI                           #\n"
    printf "#################################################\n"

    ls -al
    cd tooling-ci/demo
    ./mvnw clean package
